package com.drawnblue.dao;

import com.drawnblue.entity.GoodsPackAffiliated;
import com.drawnblue.entity.GoodsPackAffiliatedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsPackAffiliatedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(GoodsPackAffiliatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(GoodsPackAffiliatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(GoodsPackAffiliated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(GoodsPackAffiliated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<GoodsPackAffiliated> selectByExample(GoodsPackAffiliatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    GoodsPackAffiliated selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsPackAffiliated record, @Param("example") GoodsPackAffiliatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") GoodsPackAffiliated record, @Param("example") GoodsPackAffiliatedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsPackAffiliated record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pack_affiliated
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(GoodsPackAffiliated record);
}