package com.drawnblue.dao;

import com.drawnblue.entity.InfoAnnexes;
import com.drawnblue.entity.InfoAnnexesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoAnnexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(InfoAnnexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(InfoAnnexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<InfoAnnexes> selectByExample(InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    InfoAnnexes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") InfoAnnexes record, @Param("example") InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") InfoAnnexes record, @Param("example") InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(InfoAnnexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_annexes
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(InfoAnnexes record);
}