package com.drawnblue.dao;

import com.drawnblue.entity.LeaveMessage;
import com.drawnblue.entity.LeaveMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaveMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<LeaveMessage> selectByExampleWithBLOBs(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<LeaveMessage> selectByExample(LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    LeaveMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") LeaveMessage record, @Param("example") LeaveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(LeaveMessage record);
}