package com.drawnblue.dao;

import com.drawnblue.entity.UploadTemp;
import com.drawnblue.entity.UploadTempExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UploadTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UploadTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UploadTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UploadTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UploadTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UploadTemp> selectByExample(UploadTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UploadTemp record, @Param("example") UploadTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uploadtemp
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UploadTemp record, @Param("example") UploadTempExample example);
}