package com.drawnblue.dao;

import com.drawnblue.entity.UserAccountLogB;
import com.drawnblue.entity.UserAccountLogBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountLogBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserAccountLogBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserAccountLogBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(Long accountlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserAccountLogB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserAccountLogB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserAccountLogB> selectByExample(UserAccountLogBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserAccountLogB selectByPrimaryKey(Long accountlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAccountLogB record, @Param("example") UserAccountLogBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserAccountLogB record, @Param("example") UserAccountLogBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserAccountLogB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_log_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserAccountLogB record);
}