package com.drawnblue.dao;

import com.drawnblue.entity.UserAccountB;
import com.drawnblue.entity.UserAccountBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserAccountBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserAccountBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserAccountB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserAccountB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserAccountB> selectByExample(UserAccountBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserAccountB selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAccountB record, @Param("example") UserAccountBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserAccountB record, @Param("example") UserAccountBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserAccountB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_201404
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserAccountB record);
}