package com.drawnblue.dao;

import com.drawnblue.entity.UserCash;
import com.drawnblue.entity.UserCashExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(String cashId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserCash> selectByExample(UserCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserCash selectByPrimaryKey(String cashId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserCash record, @Param("example") UserCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserCash record, @Param("example") UserCashExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cash
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserCash record);
}