package com.drawnblue.dao;

import com.drawnblue.entity.UserPlace;
import com.drawnblue.entity.UserPlaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPlaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(String placeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserPlace> selectByExample(UserPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserPlace selectByPrimaryKey(String placeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPlace record, @Param("example") UserPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserPlace record, @Param("example") UserPlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserPlace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_place
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserPlace record);
}