package com.drawnblue.dao;

import com.drawnblue.entity.UserPoint;
import com.drawnblue.entity.UserPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(String pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserPoint> selectByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserPoint selectByPrimaryKey(String pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPoint record, @Param("example") UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserPoint record, @Param("example") UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserPoint record);
}