package com.drawnblue.dao;

import com.drawnblue.entity.UserBuy;
import com.drawnblue.entity.UserBuyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBuyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(String buyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserBuy> selectByExample(UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserBuy selectByPrimaryKey(String buyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserBuy record, @Param("example") UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserBuy record, @Param("example") UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_buy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserBuy record);
}