package com.drawnblue.dao;

import com.drawnblue.entity.UserPairA;
import com.drawnblue.entity.UserPairAExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPairAMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    long countByExample(UserPairAExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByExample(UserPairAExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int deleteByPrimaryKey(String pairId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insert(UserPairA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int insertSelective(UserPairA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    List<UserPairA> selectByExample(UserPairAExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    UserPairA selectByPrimaryKey(String pairId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPairA record, @Param("example") UserPairAExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByExample(@Param("record") UserPairA record, @Param("example") UserPairAExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKeySelective(UserPairA record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pair_201312
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    int updateByPrimaryKey(UserPairA record);
}